package snapper

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// The limine fixtures are reconstructions, not captures. Unlike the snapper
// samples in testdata, there is no public dump of a generated
// /boot/limine.conf to paste in, so these were rebuilt line by line from the
// writer that produces them (limine-snapper-sync's LimineWriter, which fixes
// every literal: the "Snapshots" node name, the slash depths, the ### banner,
// the `comment:` line and the eight title formats) and from limine's own
// CONFIG.md for the grammar. The three layouts below are the ones that
// writer can emit, including Omarchy's timestamp-only titles.

// snapshotsInsideOS is the default layout: the Snapshots subtree lives inside
// the operating system's entry, so it sits at depth 2 and its snapshots at
// depth 3. Note the deliberately inconsistent indentation — two spaces for
// the kernel entries, five for the generated block — which is why depth is
// read from the slashes and never from the leading whitespace.
const snapshotsInsideOS = `### Read more at config document: https://github.com/limine-bootloader/limine
timeout: 3
default_entry: 2

/Arch Linux

  //Kernel
  protocol: linux
  module_path: boot():/initramfs-linux.img
  kernel_path: boot():/vmlinuz-linux
  kernel_cmdline: rw rootflags=subvol=/@ root=UUID=068589c1-d9be-407c-ad86-101aa0912825

  //Snapshots
     ### Auto-generated by limine-snapper-sync
     comment: 3 / 15 snapshots
     ///ID=112 2026-08-25 10:59:59
     comment: pacman -Syu
     ////Kernel
     protocol: linux
     module_path: boot():/d647abee/limine_history/initramfs-linux.img_sha256_9f2b7c
     kernel_path: boot():/d647abee/limine_history/vmlinuz-linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/112/snapshot root=UUID=068589c1
     ///ID=111 2026-08-25 10:59:58
     comment: before the nvidia downgrade
     ////Kernel
     protocol: linux
     kernel_path: boot():/d647abee/limine_history/vmlinuz-linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/111/snapshot root=UUID=068589c1
     ///ID=110 2026-08-24 08:12:03
     comment: timeline
     ////Kernel
     protocol: linux
     kernel_path: boot():/d647abee/limine_history/vmlinuz-linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/110/snapshot root=UUID=068589c1
`

// snapshotsOutsideOS is the other supported layout: /Snapshots is a top-level
// entry with one node per operating system under it, so the snapshots are one
// level deeper. The per-OS node must not be mistaken for a snapshot.
const snapshotsOutsideOS = `timeout: 3

/+Arch Linux
comment: machine-id=d647abee

  //Mainline kernel
  protocol: linux
  kernel_path: boot():/d647abee/kernel-version/linux
  kernel_cmdline: rw rootflags=subvol=/@ root=UUID=068589c1

/Snapshots
     //Arch Linux
     ### Auto-generated by limine-snapper-sync
     comment: 2 / 15 snapshots
     comment: machine-id=d647abee
     ///ID=112 2026-08-25 10:59:59
     comment: pacman -Syu
     ////Mainline kernel
     protocol: linux
     kernel_path: boot():/d647abee/limine_history/linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/112/snapshot root=UUID=068589c1
     ///ID=111 2026-08-25 10:59:58
     comment: timeline
     ////Mainline kernel
     protocol: linux
     kernel_path: boot():/d647abee/limine_history/linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/111/snapshot root=UUID=068589c1
`

// omarchyLayout is what Omarchy ships: unified kernel images, and
// SNAPSHOT_FORMAT_CHOICE=5, which puts the timestamp alone in the title with
// no ID at all. The snapshot number is then only recoverable from the boot
// line's rootflags, which is exactly what the parser falls back to.
const omarchyLayout = `timeout: 3

/+Omarchy
### This OS entry is auto-generated by limine-entry-tool
comment: machine-id=d647abee order-priority=50

  //omarchy
  comment: kernel-id=omarchy
  protocol: efi
  path: boot():/EFI/Linux/omarchy.efi#8a1cd4

  //Snapshots
     ### Auto-generated by limine-snapper-sync
     comment: 2 / 5 snapshots
     ///2026-08-25 10:59:59
     comment: pacman -Syu
     ////omarchy
     protocol: efi
     path: boot():/d647abee/limine_history/omarchy.efi_sha256_4c7e19
     cmdline: rw rootflags=subvol=/@/.snapshots/112/snapshot root=UUID=068589c1 quiet splash
     ///2026-08-24 08:12:03
     comment: timeline
     ////omarchy
     protocol: efi
     path: boot():/d647abee/limine_history/omarchy.efi_sha256_4c7e19
     cmdline: rw rootflags=subvol=/@/.snapshots/110/snapshot root=UUID=068589c1 quiet splash
`

func TestParseBootEntries(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  []BootEntry
	}{
		{
			name:  "the Snapshots subtree inside the OS entry",
			input: snapshotsInsideOS,
			want: []BootEntry{
				{Title: "ID=112 2026-08-25 10:59:59", Number: 112, Comment: "pacman -Syu"},
				{Title: "ID=111 2026-08-25 10:59:58", Number: 111,
					Comment: "before the nvidia downgrade"},
				{Title: "ID=110 2026-08-24 08:12:03", Number: 110, Comment: "timeline"},
			},
		},
		{
			name:  "a top-level Snapshots entry with a node per operating system",
			input: snapshotsOutsideOS,
			want: []BootEntry{
				{Title: "ID=112 2026-08-25 10:59:59", Number: 112, Comment: "pacman -Syu"},
				{Title: "ID=111 2026-08-25 10:59:58", Number: 111, Comment: "timeline"},
			},
		},
		{
			name:  "Omarchy's timestamp-only titles, with the number in the cmdline",
			input: omarchyLayout,
			want: []BootEntry{
				{Title: "2026-08-25 10:59:59", Number: 112, Comment: "pacman -Syu"},
				{Title: "2026-08-24 08:12:03", Number: 110, Comment: "timeline"},
			},
		},
		{
			name: "a configuration with no Snapshots subtree",
			input: "timeout: 3\n\n/Arch Linux\nprotocol: linux\n" +
				"kernel_path: boot():/vmlinuz-linux\n",
			want: nil,
		},
		{
			name:  "an empty file",
			input: "",
			want:  nil,
		},
		{
			name: "a Snapshots node the sync tool has not filled in yet",
			input: "/Arch Linux\n  //Kernel\n  protocol: linux\n" +
				"  //Snapshots\n     ### Auto-generated by limine-snapper-sync\n" +
				"     comment: 0 / 15 snapshots\n",
			want: nil,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := ParseBootEntries(tc.input)
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("got %+v, want %+v", got, tc.want)
			}
		})
	}
}

func TestParseBootEntriesIgnoresComments(t *testing.T) {
	// A '#' line is a comment wherever it appears, including the ### banner
	// the sync tool writes, so it must never be read as an entry.
	entries := ParseBootEntries("# /Snapshots\n# ///ID=1 fake\n/Arch\nprotocol: linux\n")
	if entries != nil {
		t.Errorf("a commented-out subtree produced %+v", entries)
	}
}

func TestReadBootEntries(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "limine.conf")
	if err := os.WriteFile(path, []byte(omarchyLayout), 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}
	entries, err := ReadBootEntries(path)
	if err != nil {
		t.Fatalf("ReadBootEntries: %v", err)
	}
	if len(entries) != 2 {
		t.Errorf("got %d entries, want 2", len(entries))
	}

	// A machine with no limine simply has no boot entries: that is an answer,
	// not a failure the rollback screen should report as an error.
	entries, err = ReadBootEntries(filepath.Join(dir, "nothing-here.conf"))
	if err != nil || entries != nil {
		t.Errorf("a missing file gave (%+v, %v), want (nil, nil)", entries, err)
	}
	if entries, err := ReadBootEntries(""); err != nil || entries != nil {
		t.Errorf("an unset path gave (%+v, %v), want (nil, nil)", entries, err)
	}
}
