package snapper

import (
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

// The three constants below are reconstructions, not captures: they were
// rebuilt line by line from the writer that produces them
// (limine-snapper-sync's LimineWriter, which fixes every literal: the
// "Snapshots" node name, the slash depths, the ### banner, the `comment:`
// line and the title formats) and from limine's own CONFIG.md for the
// grammar. They cover the layouts that writer can emit.
//
// testdata/limine-omarchy-server.conf is the real thing beside them: a
// verbatim /boot/limine.conf captured in tui-lab from an Omarchy Server 4.0.1
// VM after four `snapper -c root create` calls and one `limine-snapper-sync`
// run. See TestParseBootEntriesOmarchyCapture for what that run proved.

// snapshotsInsideOS is the default layout: the Snapshots subtree lives inside
// the operating system's entry, so it sits at depth 2 and its snapshots at
// depth 3. Note the deliberately inconsistent indentation — two spaces for
// the kernel entries, five for the generated block — which is why depth is
// read from the slashes and never from the leading whitespace.
const snapshotsInsideOS = `### Read more at config document: https://github.com/limine-bootloader/limine
timeout: 3
default_entry: 2

/Arch Linux

  //Kernel
  protocol: linux
  module_path: boot():/initramfs-linux.img
  kernel_path: boot():/vmlinuz-linux
  kernel_cmdline: rw rootflags=subvol=/@ root=UUID=068589c1-d9be-407c-ad86-101aa0912825

  //Snapshots
     ### Auto-generated by limine-snapper-sync
     comment: 3 / 15 snapshots
     ///ID=112 2026-08-25 10:59:59
     comment: pacman -Syu
     ////Kernel
     protocol: linux
     module_path: boot():/d647abee/limine_history/initramfs-linux.img_sha256_9f2b7c
     kernel_path: boot():/d647abee/limine_history/vmlinuz-linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/112/snapshot root=UUID=068589c1
     ///ID=111 2026-08-25 10:59:58
     comment: before the nvidia downgrade
     ////Kernel
     protocol: linux
     kernel_path: boot():/d647abee/limine_history/vmlinuz-linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/111/snapshot root=UUID=068589c1
     ///ID=110 2026-08-24 08:12:03
     comment: timeline
     ////Kernel
     protocol: linux
     kernel_path: boot():/d647abee/limine_history/vmlinuz-linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/110/snapshot root=UUID=068589c1
`

// snapshotsOutsideOS is the other supported layout: /Snapshots is a top-level
// entry with one node per operating system under it, so the snapshots are one
// level deeper. The per-OS node must not be mistaken for a snapshot.
const snapshotsOutsideOS = `timeout: 3

/+Arch Linux
comment: machine-id=d647abee

  //Mainline kernel
  protocol: linux
  kernel_path: boot():/d647abee/kernel-version/linux
  kernel_cmdline: rw rootflags=subvol=/@ root=UUID=068589c1

/Snapshots
     //Arch Linux
     ### Auto-generated by limine-snapper-sync
     comment: 2 / 15 snapshots
     comment: machine-id=d647abee
     ///ID=112 2026-08-25 10:59:59
     comment: pacman -Syu
     ////Mainline kernel
     protocol: linux
     kernel_path: boot():/d647abee/limine_history/linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/112/snapshot root=UUID=068589c1
     ///ID=111 2026-08-25 10:59:58
     comment: timeline
     ////Mainline kernel
     protocol: linux
     kernel_path: boot():/d647abee/limine_history/linux_sha256_4c7e19
     kernel_cmdline: rw rootflags=subvol=/@/.snapshots/111/snapshot root=UUID=068589c1
`

// timestampOnlyLayout is the unified-kernel-image shape with
// SNAPSHOT_FORMAT_CHOICE=5, which puts the timestamp alone in the title with
// no number at all. The snapshot number is then only recoverable from the
// boot line's rootflags, which is exactly what the parser falls back to.
//
// This was written believing it was Omarchy's own format. The capture in
// testdata proved otherwise — Omarchy Server 4.0.1 leads with the number —
// so this now stands for the format choice rather than for that distribution.
const timestampOnlyLayout = `timeout: 3

/+Omarchy
### This OS entry is auto-generated by limine-entry-tool
comment: machine-id=d647abee order-priority=50

  //omarchy
  comment: kernel-id=omarchy
  protocol: efi
  path: boot():/EFI/Linux/omarchy.efi#8a1cd4

  //Snapshots
     ### Auto-generated by limine-snapper-sync
     comment: 2 / 5 snapshots
     ///2026-08-25 10:59:59
     comment: pacman -Syu
     ////omarchy
     protocol: efi
     path: boot():/d647abee/limine_history/omarchy.efi_sha256_4c7e19
     cmdline: rw rootflags=subvol=/@/.snapshots/112/snapshot root=UUID=068589c1 quiet splash
     ///2026-08-24 08:12:03
     comment: timeline
     ////omarchy
     protocol: efi
     path: boot():/d647abee/limine_history/omarchy.efi_sha256_4c7e19
     cmdline: rw rootflags=subvol=/@/.snapshots/110/snapshot root=UUID=068589c1 quiet splash
`

func TestParseBootEntries(t *testing.T) {
	tests := []struct {
		name  string
		input string
		want  []BootEntry
	}{
		{
			name:  "the Snapshots subtree inside the OS entry",
			input: snapshotsInsideOS,
			want: []BootEntry{
				{Title: "ID=112 2026-08-25 10:59:59", Number: 112, Comment: "pacman -Syu"},
				{Title: "ID=111 2026-08-25 10:59:58", Number: 111,
					Comment: "before the nvidia downgrade"},
				{Title: "ID=110 2026-08-24 08:12:03", Number: 110, Comment: "timeline"},
			},
		},
		{
			name:  "a top-level Snapshots entry with a node per operating system",
			input: snapshotsOutsideOS,
			want: []BootEntry{
				{Title: "ID=112 2026-08-25 10:59:59", Number: 112, Comment: "pacman -Syu"},
				{Title: "ID=111 2026-08-25 10:59:58", Number: 111, Comment: "timeline"},
			},
		},
		{
			name:  "timestamp-only titles, with the number in the cmdline",
			input: timestampOnlyLayout,
			want: []BootEntry{
				{Title: "2026-08-25 10:59:59", Number: 112, Comment: "pacman -Syu"},
				{Title: "2026-08-24 08:12:03", Number: 110, Comment: "timeline"},
			},
		},
		{
			name: "a configuration with no Snapshots subtree",
			input: "timeout: 3\n\n/Arch Linux\nprotocol: linux\n" +
				"kernel_path: boot():/vmlinuz-linux\n",
			want: nil,
		},
		{
			name:  "an empty file",
			input: "",
			want:  nil,
		},
		{
			name: "a Snapshots node the sync tool has not filled in yet",
			input: "/Arch Linux\n  //Kernel\n  protocol: linux\n" +
				"  //Snapshots\n     ### Auto-generated by limine-snapper-sync\n" +
				"     comment: 0 / 15 snapshots\n",
			want: nil,
		},
	}

	for _, tc := range tests {
		t.Run(tc.name, func(t *testing.T) {
			got := ParseBootEntries(tc.input)
			if !reflect.DeepEqual(got, tc.want) {
				t.Errorf("got %+v, want %+v", got, tc.want)
			}
		})
	}
}

// TestParseBootEntriesOmarchyCapture replays the real /boot/limine.conf, and
// exists because the reconstructions above got three things wrong about the
// machine they were modelling:
//
//   - the title is `4 │ 2026-08-29 21:27:27` — the snapshot number, a U+2502
//     separator, then the timestamp — and not the timestamp alone;
//   - the Snapshots node's own comment reads "4 snapshots", with no "/ 15"
//     retention figure;
//   - the generated block is indented five spaces while sitting at depth 2,
//     a sibling of the two-space `//linux` entry, which is the strongest
//     possible argument for reading depth from the slashes alone.
//
// What the reconstructions had right, and matters most: `rootflags=subvol=`
// carries the absolute `/@/.snapshots/<n>/snapshot` shape in the snapshot
// entries even though the live entry above them uses a bare `subvol=@`.
func TestParseBootEntriesOmarchyCapture(t *testing.T) {
	data, err := os.ReadFile(filepath.Join("testdata", "limine-omarchy-server.conf"))
	if err != nil {
		t.Fatalf("read the capture: %v", err)
	}
	got := ParseBootEntries(string(data))
	want := []BootEntry{
		{Title: "4 │ 2026-08-29 21:27:27", Number: 4, Comment: "lab manual"},
		{Title: "3 │ 2026-08-29 21:27:27", Number: 3, Comment: "pacman -Syu"},
		{Title: "2 │ 2026-08-29 21:27:27", Number: 2, Comment: "pacman -Syu"},
		{Title: "1 │ 2026-08-29 21:27:27", Number: 1, Comment: "lab baseline"},
	}
	if !reflect.DeepEqual(got, want) {
		t.Errorf("got %+v, want %+v", got, want)
	}

	// The `/EFI fallback` entry after the subtree, and the `//linux` entry
	// before it, are boot entries but not snapshots. Four entries is also the
	// assertion that neither leaked in.
	if len(got) != 4 {
		t.Errorf("got %d entries, want the 4 snapshots and nothing else", len(got))
	}
}

// TestSnapshotNumberFromTitle covers the number being read from the title
// itself rather than from a child's rootflags, which is what the capture's
// format allows and what keeps an entry whose kernel line is missing from
// losing its number.
func TestSnapshotNumberFromTitle(t *testing.T) {
	tests := []struct {
		title string
		want  int
	}{
		{"ID=112 2026-08-25 10:59:59", 112},
		{"4 │ 2026-08-29 21:27:27", 4},
		{"112 | 2026-08-29 21:27:27", 112},
		// A timestamp-only title has no separator, so nothing is read from
		// it and the year must not be mistaken for a snapshot number.
		{"2026-08-25 10:59:59", 0},
		{"", 0},
	}
	for _, tc := range tests {
		entries := []limineEntry{{depth: 3, title: tc.title, options: map[string]string{}}}
		if got := snapshotNumber(entries, 0); got != tc.want {
			t.Errorf("snapshotNumber(%q) = %d, want %d", tc.title, got, tc.want)
		}
	}
}

func TestParseBootEntriesIgnoresComments(t *testing.T) {
	// A '#' line is a comment wherever it appears, including the ### banner
	// the sync tool writes, so it must never be read as an entry.
	entries := ParseBootEntries("# /Snapshots\n# ///ID=1 fake\n/Arch\nprotocol: linux\n")
	if entries != nil {
		t.Errorf("a commented-out subtree produced %+v", entries)
	}
}

func TestReadBootEntries(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "limine.conf")
	if err := os.WriteFile(path, []byte(timestampOnlyLayout), 0o600); err != nil {
		t.Fatalf("write: %v", err)
	}
	entries, err := ReadBootEntries(path)
	if err != nil {
		t.Fatalf("ReadBootEntries: %v", err)
	}
	if len(entries) != 2 {
		t.Errorf("got %d entries, want 2", len(entries))
	}

	// A machine with no limine simply has no boot entries: that is an answer,
	// not a failure the rollback screen should report as an error.
	entries, err = ReadBootEntries(filepath.Join(dir, "nothing-here.conf"))
	if err != nil || entries != nil {
		t.Errorf("a missing file gave (%+v, %v), want (nil, nil)", entries, err)
	}
	if entries, err := ReadBootEntries(""); err != nil || entries != nil {
		t.Errorf("an unset path gave (%+v, %v), want (nil, nil)", entries, err)
	}
}
